# Generated by Django 4.2.1 on 2023-05-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitybikeRides',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_time', models.DateTimeField()),
                ('ret_time', models.DateTimeField()),
                ('dep_station_name', models.CharField(max_length=50)),
                ('ret_station_name', models.CharField(max_length=50)),
                ('dist', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'citybike_rides',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitybikeStations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_fi', models.CharField(max_length=50, unique=True)),
                ('name_se', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('address_fi', models.CharField(max_length=50)),
                ('address_se', models.CharField(max_length=50)),
                ('city_fi', models.CharField(max_length=25)),
                ('city_se', models.CharField(max_length=25)),
                ('bike_operator', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
            ],
            options={
                'db_table': 'citybike_stations',
                'managed': False,
            },
        ),
    ]
