# Generated by Django 4.2.1 on 2023-05-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citybikerides',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='citybikestations',
            options={'managed': True},
        ),
    ]
